# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
