# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 09:36
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default='/media/featured_post_images/default-featured-image.png', null=True, upload_to=blog.models.upload_location),
        ),
    ]
