# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:10
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161031_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_desc',
            field=models.CharField(blank=True, help_text='This must not be more than 160 characters.', max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text="This will be auto generated from 'Title', you can also modify it if you want to.", max_length=58, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='This must not be more than 58 characters.', max_length=58, unique=True),
        ),
    ]
