# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161031_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_desc',
            field=models.CharField(blank=True, help_text='This must not be more than 160 characters.', max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text="This will be auto generated from 'Title', you can also modify it if you want to.", max_length=58, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_desc',
            field=models.CharField(blank=True, help_text='This must not be more than 160 characters.', max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_title',
            field=models.CharField(blank=True, help_text="This will be auto generated from 'Title', you can also modify it if you want to.", max_length=58, null=True, unique=True),
        ),
    ]
