# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161101_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text="This will be auto generated from 'Title' if you leave it empty, you can also modify it if you want to.", max_length=58, null=True, unique=True),
        ),
    ]
