# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161111_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='seo_title',
        ),
        migrations.AddField(
            model_name='post',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Must contain comma seperated list of key words.', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
